### ISSUE TITLE
First Version TODO List:

### ISSUE THREAD

**Issue by sean6bucks** [sean6bucks/skunq_chat#1]
### User Login

- [x] Show Login Shade and fetch localStorage User Data
- [x] If no Local, show login panel
- [x] If user data already set OR user logs in show loader and fetch chat data
- [x] Set User Data to local storage for next session
- [x] Animate shade to break away ( panel drops out )

### Initial Data Fetch

- [x] Call backend for users and save as friends list
- [x] Check local if any chats are saved and render chats list
- [x] Check for messages for each chat in list and show badge if any new.

### Create CRUD functions and views

- [x] Add "Create Chat" function that opens new chat view and saves data to current_user
- [ ] Add "delete Chat" to remove chat window from chats list - but save data for re-open
- [x] Add "Create Group" function to allow for a new chat with multiple chatters

### Chat Window

- [x] Add input bar with send button and "enter" trigger
- [x] On send message add message to chat log
- [x] On new chat create polling loop for new messages from specific user

**Comment by sean6bucks** [comment]
Not endpoint for Delete so closing this ticket
